import { 
    GoogleGenerativeAI, 
    HarmCategory, 
    HarmBlockThreshold 
  } from "@google/generative-ai";
  
  class GeminiService {
    private static instance: GeminiService | null = null;
    private genAI?: GoogleGenerativeAI;
  
    private constructor() {
      const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
      if (!apiKey) {
        console.warn("⚠ Warning: Gemini API key is missing. Chatbot functionality may be limited.");
        return;
      }
      
      this.genAI = new GoogleGenerativeAI(apiKey);
    }
  
    public static getInstance(): GeminiService {
      if (!GeminiService.instance) {
        GeminiService.instance = new GeminiService();
      }
      return GeminiService.instance;
    }
  
    public async generateResponse(prompt: string): Promise<string> {
      if (!this.genAI) {
        return "🚨 Error: Gemini API is not initialized due to a missing API key.";
      }
  
      try {
        const model = this.genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest" });
  
        const generationConfig = {
          temperature: 0.85,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        };
  
        const safetySettings = [
          { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
          { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
        ];
  
        // 🔹 Improve prompt structuring
        let formattedPrompt = `
        You are a knowledgeable AI assistant. Respond concisely but informatively. 
  
        Guidelines:
        - Use bullet points where appropriate.
        - Ensure responses are formatted clearly with bold headings.
        - Maintain professional but conversational tone.
  
        ${prompt.trim()}
        `;
  
        console.log("📌 Formatted Prompt:", formattedPrompt);
  
        const result = await model.generateContent({
          contents: [{ role: "user", parts: [{ text: formattedPrompt }] }],
          generationConfig,
          safetySettings,
        });
  
        // 🔹 Extract response correctly
        const response = result.response;
        if (!response?.candidates?.length) {
          return "⚠ No response generated by the model.";
        }
  
        const responseCandidate = response.candidates?.[0];
        const responseParts = responseCandidate?.content?.parts || [];
        let responseText = responseParts.map(part => part.text).join("\n").trim();
  
        console.log("📌 Raw Gemini API Response:", JSON.stringify(response, null, 2));
  
        // 🔹 Format response for better readability
       // 🔹 Ensure response is properly formatted
       responseText = responseText
       .replace(/•\s*/g, "\n\n• ")  // Ensure bullet points start on a new line
       .replace(/\\(.?)\\/g, "\n\n$1*\n") // Ensure bold text starts on a new line
       .replace(/(\.\s*)•/g, "\n\n•") // Fix bullet points after a period
       .replace(/\n{2,}/g, "\n\n") // Ensure no excessive new lines
       .trim();
     
  
        return responseText;
      } catch (error) {
        console.error("❌ Gemini API Error:", error);
  
        if (error instanceof Error) {
          return "🚨 Error: ${error.message}. Please check API key and network.";
        }
  
        return "⚠ An unexpected error occurred while generating a response.";
      }
    }
  }
  
  export default GeminiService;